services:
  ansible:
    container_name: ansible
    image: apurwasingh/cansible
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deploy.yml:/root/deploy.yml
    tty: true
    networks:
      - jenkins_net

  jenkins:
    container_name: jenkins
    image: apurwasingh/djentle
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins_net:
    name: jenkins_net
    driver: bridge
